- lib/school_house_web/templates/layout/_lesson_menu.html.leex
This fixes this HTML issue on the lesson menu:
https://rocketvalidator.com/s/5a71bc62-29c6-4e85-9ce5-2af0513f1976/i/106525604
The problem was in this structure:
```html
<ul>
<h3>Ecto</h3>
<li>1.- Introduction</li>
<li>2.- Changesets</li>
</ul>
```
This was invalid as an `<ul>` element expects only `<li>` elements as direct children.
Instead, I propose this structure using nested lists. I'm also using `<ol>` for the nested lists, as they're in fact _ordered lists_
```html
<ul>
<li>
<p>Ecto</p>
<ol>
<li>1.- Introduction</li>
<li>2.- Changesets</li>
</ol>
</li>
<li>
<p>Storage</p>
<ol>
<li>1.- ETS</li>
<li>2.- Mnesia</li>
</ol>
</li>
</ul>
```
> fixes HTML structure on lesson menu

- config/prod.exs
Hi! Related to https://github.com/elixirschool/school_house/issues/22 I think I've found the cause, it looks like `config/prod.exs` needed some attention as per [this guide](https://hexdocs.pm/phoenix/heroku.html#making-our-project-ready-for-heroku).
> configures production as explained in guides for Heroku

- lib/school_house_web/templates/lesson/_section_header.html.eex
Closes #11, this PR simply replaces the string "top of page" with an arrow.
> Update scroll to top link with an arrow

- config/lessons.exs
This is partially responsible for #26 but there is a greater bug there that needs addressing. This PR just corrects the misconfigured value.
> Correct invalid lesson name in configuration

- lib/school_house_web/templates/layout/_locale_menu.html.leex
- lib/school_house_web/views/html_helpers.ex
- test/school_house_web/views/html_helpers_test.exs
Update the function to `_url` from `_link` to more accurately reflect
what it does. Only modify the request path, the entire url is not
necessary. 
Fixes #22.
> We only need to modify the path

- assets/css/app.css
- assets/tailwind.config.js
- lib/school_house_web/templates/lesson/_pagination.html.eex
- lib/school_house_web/templates/lesson/lesson.html.eex
This one closes #5 by adding a section to the footer for the next and previous lesson.
> Add a prev and next link to lessons template

- lib/school_house_web/controllers/post_controller.ex
- lib/school_house_web/templates/post/post.html.eex
- test/school_house_web/controllers/post_controller_test.exs
This pr updates the post controller to return a `conn` even when the post is not found. The view now handles the case where the post assign is nil by displaying a user-friendly error message.
Closes #27.
**Dark** 🌔 
**Light** ☀️
> Show An Error Message When Blog Post Is Not Found [Closes #27]

- assets/css/app.css
- assets/js/app.js
- assets/js/dark-mode.js
- assets/js/menu-toggle.js
- assets/tailwind.config.js
- lib/school_house_web/templates/layout/_dark_mode_toggle.html.leex
- lib/school_house_web/templates/layout/_header.html.leex
- lib/school_house_web/templates/layout/_lesson_menu.html.leex
- lib/school_house_web/templates/lesson/lesson.html.eex
- lib/school_house_web/templates/page/index.html.eex
- lib/school_house_web/templates/page/why.html.eex
- lib/school_house_web/templates/post/index.html.eex
Addresses #9 .
The primary focus of this pr is to update the header element to be more responsive. There are some other tweaks to page layouts to eliminate awkward gaps on smaller screens.
It turns out there were not many changes needed for the lessons menu!
I have added a few screenshots here taken from Chrome using the iPhone X viewport setting. I tested this with the iPad size and iPhone 5/SE screen size as well. Let me know if there are issues with specific device types/browsers that you can think of!
Also more generally if you think the layout of the menu should be different I am happy to make changes.
> Improve Responsiveness

- .dockerignore
- Dockerfile
- Makefile
I updated the `Dockerfile`, `Makefile` and `.dockerignore` files to hopefully resolve GH actions failure (#66).
The primary reason that the build failed was that the `Makefile` was not found when `make content` was run. After that, I ran into issues trying to use a symlink for the image assets with docker. I ultimately settled on just `COPY`-ing the image assets.
I moved the symlink to the `make setup` command so users can still use it for their dev environment and the Dockerfile can still use `make content`.
Happy to play around with the Dockerfile if there a different preferred way to write this.
> Update Dockerfile to Resolve Deploy Issue

- assets/css/app.css
- assets/js/dark-mode.js
- assets/tailwind.config.js
- lib/school_house_web/controllers/lesson_controller.ex
- lib/school_house_web/controllers/page_controller.ex
- lib/school_house_web/controllers/post_controller.ex
- lib/school_house_web/templates/layout/_dark_mode_toggle.html.leex
- lib/school_house_web/templates/layout/_header.html.leex
- lib/school_house_web/templates/page/_newsletter.html.eex
- lib/school_house_web/templates/page/index.html.eex
- lib/school_house_web/templates/post/post.html.eex
Addresses (but does not close) #35
* Updated the colors used on the website to increase the contrast between text and background to meet WCAG 2 AA contrast thresholds.
* Updated the dark mode toggle to not use a label as a wrapper element. Further improved accessibility of this control by labeling the input itself.
* Added page titles to controllers that were missing them
* Converted some `p` and `span` tags to header tags to better semantically describe the content
> Update Colors And Dark Mode Toggle to Improve A11Y

- Dockerfile
Updated the Dockerfile to include libstdc++ dependency as it is now required after upgrading the base image from `elixir:1.10.0-alpine` -> `elixir:1.12.0-alpine`.
> Add libstdc++ Dependency to Docker Image

- lib/school_house_web/templates/page/index.html.eex
This pr adds a section the home page to show stats about Elixir's adoption and closes #55.
The copy could probably be tweaked, so I welcome any feedback on that (as well as the code itself 😅)!
I went down a little bit of a rabbit hole trying to come up with a stat for the number of courses offered and couldn't find a good source for it, so I left it out of this. I am happy to add it though if anyone has suggestions for that stat!
> Add 'By The Numbers' Section to Home Page

- mix.exs
This PR sets 1.12 as the Elixir version in Mix.exs
I'm not so sure about including a `.tool-versions` file as some devs may not want to use `asdf`.
> Elixir version 1.12

- lib/school_house_web/templates/page/why.html.eex
The "Why Choose Elixir" page has 65 HTML issues due to its structure:
https://rocketvalidator.com/s/7d40eccc-c4a6-4915-825e-18149434e117/p/4668014/i
The problem lies in the use of `<dl>` and nested `<div>`. It looks like it can accept one level of nested `<div>`, but no more.
As `<dl>` are intended as definition lists, and we're not really defining terms, I think we should instead rely on a simple h1 / h2 / h3 structure, because the content really is structured like this:
While its roots are in lambda calculus...
Data is not transformed...
Problems are decomposed...
The very nature...
Elixir and the BEAM...
--
... you get the idea. This gives a simpler and easier to understand structure. And it gets us from 65 HTML issues to only 5 (soon to be fixed as well), here's the report from my …
> fix HTML structure of Why page

- assets/css/app.css
- lib/school_house_web/templates/layout/_locale_menu.html.leex
There's a glitch on the locale menu, when you click on a different section the locale menu is shown unfolded until some microseconds later Alpine hides it:
https://user-images.githubusercontent.com/2629/126673357-843af530-f3c9-4d89-b53d-f18932e2ae94.mov
This PR fixes it by using the `x-cloak` directive:
See https://alpinejs.dev/directives/cloak
> fixes locale menu glitch using x-cloak

- lib/school_house/posts.ex
- lib/school_house_web/controllers/post_controller.ex
- lib/school_house_web/templates/post/post.html.eex
- lib/school_house_web/views/html_helpers.ex
- test/school_house/posts_test.exs
- test/school_house_web/controllers/post_controller_test.exs
- test/school_house_web/views/html_helpers_test.exs
This PR fixes #85 by:
* Fixing broken links generated in locale menu
* Return 404 page for Blog post not found instead of 200 with custom content.
This will make it easier for users and crawler bots to properly find the internal web pages :)
> Fix locale menu for pages outside of locale scope

- assets/js/dark-mode.js
- assets/js/initialize-theme.js
- assets/webpack.config.js
- lib/school_house_web/plugs/set_locale_plug.ex
- lib/school_house_web/templates/layout/_locale_menu.html.leex
- lib/school_house_web/templates/layout/root.html.leex
- lib/school_house_web/views/html_helpers.ex
- test/school_house_web/controllers/lesson_controller_test.exs
- test/school_house_web/views/html_helpers_test.exs
Closes #87 & #88.
Updated the dark mode logic to add a blocking js script until the theme is set to avoid a brief flicker of light mode on page load (when dark mode is enabled).
Also updated the set locale plug to check the given locale against the list of valid locales and redirect to the home page if the locale is not valid.
Finally, updated a helper function used by the locale menu to redirect the user to the expected locale when they click on one.
https://user-images.githubusercontent.com/1526888/126853018-46075f3d-529e-4320-b764-f03b13199ecd.mp4
> Fix Dark Mode Flicker and Handle Invalid Locales

- lib/school_house_web.ex
- lib/school_house_web/templates/layout/root.html.leex
phoenix_html generates invalid HTML code for this meta tag. This is going to be fixed in 3.0
but in the meantime we change it in our layout to fix our most common HTML issue on the site.
https://github.com/phoenixframework/phoenix_html/issues/294
Fixing this will close 4 W3C HTML issues present in each and every page, boosting us from 0% to [67% web pages without HTML issues](https://rocketvalidator.com/s/328d31c1-0a28-423f-88dc-64c5c0d97590)!
Fixes #94
> fixes invalid meta tag for csrf token

- Makefile
- config/config.exs
- config/redirects.exs
According to 
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
the correct 2 letter code for modern Greek is `el`, not `gr`
@doomspork maybe this should be fixed also in the main repo so when we copy content, we rename the `gr` folder to `el`. I've already done that on the Makefile, so removing the `content` folder and running `make content` again also works.
closes #97
> fixes language code for Greek

- lib/school_house_web/live/conferences_live.html.leex
This PR fixes the conference page, where the country select lacked an ID, making the `label for="country-select"` invalid as it could not be linked to the input.
Caught in https://rocketvalidator.com/s/624562a6-bdbe-4411-9c28-3652a4887982/i/112979562
> adds missing id for country select in conferences page

- lib/mix/tasks/school_house.gen.sitemap.ex
`locale` parameter should go first for lessons URL.
Fixes #105
> fixes sitemap.xml

- lib/school_house_web/templates/page/podcasts.html.eex
These images were missing an `alt` attribute to describe them, this fixes most of the issues in
https://rocketvalidator.com/s/7bc5b3d4-f96c-4aa5-aeae-7c5fab2d6560/v/15067194
The rest are missing alts in [this blog post](https://beta.elixirschool.com/blog/elixir-conf-eu-2019-review) will be fixed in the content repo.
> adds missing alt for images in podcasts page

- .gitignore
- lib/mix/tasks/school_house.gen.sitemap.ex
- lib/school_house_web/endpoint.ex
- lib/school_house_web/templates/layout/root.html.leex
- lib/school_house_web/views/layout_view.ex
- test/school_house_web/views/layout_view_test.exs
Related to #109 .
Added another sitemap file for dark mode so that Rocket Validator can validate accessibility of dark mode as well.
I am open to suggestions on this, but to handle the `ui` query parameter I added a function to `LayoutView` which I use inside the `root.html.eex` file.
> Add Sitemap Links for Dark Mode

- .github/workflows/deploy.yml
Updated the deploy.yml workflow to only attempt the deploy job when the repo is the original elixirschool instance and not a fork.
This fixes an issue where Github actions attempts to deploy code in forked repos and sends a somewhat confusing failure email when the deploy fails.
> Only Attempt a Deploy When Main Repo is Updated

- assets/css/app.css
- lib/school_house_web/templates/report/_lesson.html.eex
- lib/school_house_web/templates/report/_missing.html.eex
- lib/school_house_web/templates/report/_section.html.eex
- lib/school_house_web/templates/report/report.html.eex
- lib/school_house_web/views/html_helpers.ex
Addresses #123 
Updated report page to use colors with higher contrast in light mode and dark mode.
> Update Color Scheme on Report Page

- assets/tailwind.config.js
- lib/school_house_web/templates/lesson/_testing.html.eex
- lib/school_house_web/templates/page/_newsletter.html.eex
In the latest Rocket Validator report, there are only a [handful of color contrast issues](https://rocketvalidator.com/s/02e7c5f0-2887-47db-9e5c-f75543b80276/v/15180463) remaining for the dark theme UI. This pr should fix those!
For the light theme, the [only color contrast issue](https://rocketvalidator.com/s/5517fb81-fa1c-4cc9-a4c4-201426d8db9f/v/15179966) occurs on a page we do not have control over and does not contain critical content so I think it is worth removing that page from the report altogether: https://beta.elixirschool.com/cdn-cgi/l/email-protection .
Once this is merged, we should run one more report @jaimeiniesta and then 🤞🏼 finally be able to close #109 !
> Fix Remaining Contrast Issues for Dark Theme

- lib/school_house_web/templates/lesson/index.html.eex
Removes extra `<p>` tag in the lessons index page. This was causing an HTML validation error in Rocket Validator.
Closes #128
> Remove Extra Paragraph Tag from Lesson Section Index Page

- assets/css/app.css
- assets/tailwind.config.js
This pr updates the link color used in excerpt blocks on lesson pages to have better color contrast.
I tried to grab a before and after report on Rocket Validator, but when I ran a report on an individual [page from the report that reported the contrast issue](https://rocketvalidator.com/s/77b28abc-4e56-4d0a-83fc-51f77e0ccf1a/p/4834495/v?search=Elements+must+have+sufficient+color+contrast), Rocket Validator [found no accessibility issues](https://rocketvalidator.com/s/3c4918e7-623b-4334-8ccb-22bb482528ac) on the same page on the beta site.
> Update Excerpt Link Color, Code Blocks

- lib/school_house_web/router.ex
This is what the current site uses and it's 404ing breaking people's links: https://elixirschool.com/en/lessons/basics/basics/
> The existing site includes /lessons

- app.json
- config/prod.exs
- config/releases.exs
Should resolve #143.
Now that we are no longer in beta we don't need to prefix elixirschool.com with beta 🎉
> Update Phoenix Host to Remove Beta Subdomain

- lib/school_house_web/templates/lesson/lesson.html.heex
The URL was pointing to the wrong place. the path `lessons` should be before the location.
> Wrong URL to edit lessons

- lib/school_house_web/templates/layout/_lesson_menu.html.heex
This PR resolves the issues with lesson links mentioned in #151.
> Fix typos in lesson links

- lib/school_house_web/templates/post/index.html.heex
This PR solves #148
This should be seen as a temporary solution. I think it’s worth the price fix the access to the older posts as soon as possible even with a not so elegant solution.
I will work on a more complete solution that allows readers to choose items per page, with pagination working with tags too, an improved and responsive design and a more organized code.
> Add pagination to blog posts page

- .credo.exs
- .gitignore
- README.md
- app.json
- test/school_house/conferences_test.exs
Updated a handful of files to improve repo/dev qol:
* Enabled single pipeline rule in `.credo.exs` to enforce a stylistic rule that pops up in prs from time to time
* Added sitemap files back to the `.gitignore` since they are being generated to this location before being moved to `/priv`
* Added a link to the ElixirSchool repo in the README.md to make it more obvious where the lessons and blog posts live
* Updated the `app.json` file used by Heroku to use the correct name!
Edit: I'd be lying if I said this wasn't partially motivated by a desire to wrap up my Hacktoberfest contributions 😂
> Improve Repo Hygiene

- lib/school_house_web/templates/layout/_footer.html.heex
It is complementary work of #182 to remove headings in the footer.
https://github.com/elixirschool/school_house/pull/182#issuecomment-957261378
> Remove headings in footer

- Makefile
First, it adds content as Phony, otherwise, if the folder was present it was not getting rebuilt.
Then it adapts the conetntn command for testing locally. Allowing to run `make content` and pick up the changes when running locally.
> Fix build + make it friendly for ElixirSchool contributors

- lib/school_house_web/templates/lesson/_pagination.html.heex
This is a super small pr to fix an issue I noticed with heading alignment for the "next lesson" navigation section below each lesson.
> Fix Next Lesson Heading Alignment

- lib/school_house_web/templates/layout/_lesson_menu.html.heex
- lib/school_house_web/templates/page/why.html.heex
- priv/gettext/ar/LC_MESSAGES/default.po
- priv/gettext/bg/LC_MESSAGES/default.po
- priv/gettext/bn/LC_MESSAGES/default.po
- priv/gettext/de/LC_MESSAGES/default.po
- priv/gettext/default.pot
- priv/gettext/el/LC_MESSAGES/default.po
- priv/gettext/en/LC_MESSAGES/default.po
- priv/gettext/es/LC_MESSAGES/default.po
- priv/gettext/fr/LC_MESSAGES/default.po
- priv/gettext/id/LC_MESSAGES/default.po
- priv/gettext/it/LC_MESSAGES/default.po
- priv/gettext/ja/LC_MESSAGES/default.po
- priv/gettext/ko/LC_MESSAGES/default.po
- priv/gettext/ms/LC_MESSAGES/default.po
- priv/gettext/no/LC_MESSAGES/default.po
- priv/gettext/pl/LC_MESSAGES/default.po
- priv/gettext/pt/LC_MESSAGES/default.po
- priv/gettext/ru/LC_MESSAGES/default.po
- priv/gettext/sk/LC_MESSAGES/default.po
- priv/gettext/ta/LC_MESSAGES/default.po
- priv/gettext/th/LC_MESSAGES/default.po
- priv/gettext/tr/LC_MESSAGES/default.po
- priv/gettext/uk/LC_MESSAGES/default.po
- priv/gettext/vi/LC_MESSAGES/default.po
Added Japanese translation for what was implemented in https://github.com/elixirschool/school_house/pull/192. 
Some are referred to the existing translations in "lessons".
Also updated some small parts in the localization as well. (i.e. added missing gettext)
Contributors: @yuriamm @kuunamaka @OR-2000
> Add Japanese translation to text

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- lib/mix/tasks/school_house.gen.rss.ex
- lib/mix/tasks/school_house.gen.sitemap.ex
- mix.exs
This
- Moves dialyzer to run in CI instead of deploy
- Adds caching to all steps. I've been using this at Stord for a while and it's been pretty good. There is a `CACHE_VERSION` env value you can increment to force cache busting if you need
- Add a build step to CI that attempts to build the Dockerfile
- Adds concurrency settings to cancel any CI that is already running on a commit
> feat: update all github actions with caching

- assets/tailwind.config.js
In dark theme some code in snippets is unreadable. It's usualy relate to some bash scripts.
Example of unreadable snippet:
I guess, with white color of text this snippets read much more comfortable.
So as i can check, it shouldn't affect any other usage of 'code' snippets.
> patch: make markdown code more contrast

- lib/school_house_web/templates/report/_coming_soon.html.heex
- lib/school_house_web/views/html_helpers.ex
- priv/gettext/ar/LC_MESSAGES/default.po
- priv/gettext/bg/LC_MESSAGES/default.po
- priv/gettext/bn/LC_MESSAGES/default.po
- priv/gettext/de/LC_MESSAGES/default.po
- priv/gettext/default.pot
- priv/gettext/el/LC_MESSAGES/default.po
- priv/gettext/en/LC_MESSAGES/default.po
- priv/gettext/es/LC_MESSAGES/default.po
- priv/gettext/fr/LC_MESSAGES/default.po
- priv/gettext/id/LC_MESSAGES/default.po
- priv/gettext/it/LC_MESSAGES/default.po
- priv/gettext/ja/LC_MESSAGES/default.po
- priv/gettext/ko/LC_MESSAGES/default.po
- priv/gettext/ms/LC_MESSAGES/default.po
- priv/gettext/no/LC_MESSAGES/default.po
- priv/gettext/pl/LC_MESSAGES/default.po
- priv/gettext/pt/LC_MESSAGES/default.po
- priv/gettext/ru/LC_MESSAGES/default.po
- priv/gettext/sk/LC_MESSAGES/default.po
- priv/gettext/ta/LC_MESSAGES/default.po
- priv/gettext/th/LC_MESSAGES/default.po
- priv/gettext/tr/LC_MESSAGES/default.po
- priv/gettext/uk/LC_MESSAGES/default.po
- priv/gettext/vi/LC_MESSAGES/default.po
Noticed during the translation of the Norwegian translation file that the badge "Coming Soon" wasn't being translated. 
This text is resolved in the file changed for this PR, and was the only place that didn't call `gettext` directly. This file doesn't `use` the `:view` of `SchoolHouseWeb`, so the `Gettext` module needs to be imported manually for this to work.
Verified that it works based on the Norwegian translation that I have open in https://github.com/elixirschool/school_house/pull/201
> 🐛 Fix "Coming Soon" badge translation in Lesson popover

- lib/school_house_web/templates/page/index.html.heex
- priv/gettext/no/LC_MESSAGES/default.po
Went through all the keys in the translation file for Norwegian and translated sentences and phrases into ones commonly used in Norwegian. 
Left some technology related keywords in their original language, as some of them don't make sense to translate into their Norwegian equivalent. We use a lot of English words in our daily conversations, technologists perhaps most of all.
Added Norwegian to the list of languages on the landing page as well, and changed the order of the languages based on the alphabetical order of their locale. Hope that's fine ✌️ 
Also noticed a bug in the "coming soon" tag for each lesson in the Popover in the Navigation bar, but I'll open a new Pull Request for fixing that. 
Edit: PR for badge translation bug (https://github.com/elixirschool/school_house/pull/202)
> 🌐 Add norwegian translation for web page

- assets/js/dark-mode.js
- lib/school_house_web/templates/page/index.html.heex
- priv/gettext/no/LC_MESSAGES/default.po
Upon initial page load, users with MacBooks (and other devices that support dark mode as a system setting), the mode is set to light. This has a tendency to blast my retinas with unexpected blue light at 1AM on a Tuesday night.
The browser exposes a flag that lets us known if the user has dark mode enabled on their device, namely `prefers-color-scheme: dark`. I think this is a pretty cool feature, and thought it'd be great to use this on elixir school. 😄 
Also found an excuse to sneak in a typo fix from a previous PR that slipped through the gaps. 🙇
> Default to Device Preference for Site Theme

- priv/gettext/ko/LC_MESSAGES/default.po
intentionally left out some tech keywords and texts that would become too long or unnatural when translated.
> Add Korean translation

- lib/school_house_web/templates/lesson/lesson.html.heex
Noticed when trying to edit the `bypass.md` in `elixirschool/elixirschool` from the GitHub UI, the stale `master` ref made life hard. This should fix that.
> fix: edit this lesson on github links

- lib/school_house_web/controllers/post_controller.ex
If someone has multiple blog posts open, it currently isn't possible to distinguish them apart from the tab bar alone.
At the moment, all blog posts show up as "Blog · Elixir School".
The proposed change is for "My Post Title | Blog · Elixir School".
> Show post title in page title for post specific tab names

- lib/school_house_web/templates/post/post.html.heex
It'd be great to include the date posts were first created in the blog posts themselves. This is generally helpful to get an idea of how "up to date" the code examples will be. Even better would be to nudge authors to specify the versions of Elixir, Phoenix, LiveView, etc. used in the code examples.
> Update post.html.heex to include date of post

- assets/js/app.js
- assets/js/pickup.js
- lib/school_house_web/templates/layout/root.html.heex
I've implemented a new feature in a file called `pickup.js` that saves the last point in the lessons that a user has read. This feature is designed to enhance the user experience by allowing them to easily pick up where they left off in their learning journey.
It saves the pathname and the scrolled value of the last visited lesson and continues at that point 
- Added a function in pickup.js to store the last read lesson point in local storage.
- Modified the homepage to display a message that guides users to continue their lessons from the last read point.
I found it difficult to remember where I left off in a series of lessons. So I thought I should contribute
---
Here is a gif demonstrating how it works
> Lesson Checkpoint Feature: Display Last Read Point on Homepage

- assets/tailwind.config.js
Added some spacing between link text and its underline decoration.
Left side showing current style, right is the new style:
> Added some spacing for underline decorations

- lib/school_house_web/templates/page/get_involved.html.heex
- priv/gettext/ko/LC_MESSAGES/default.po
👋 hello from a long-time admirer and :octocat: staff.
This PR fixes the company name from `Github` to `GitHub` 🙇 
thanks for all you do here 💖
> Fix the casing on GitHub

- priv/gettext/ja/LC_MESSAGES/default.po
> Correct typo in TIL typed in Japanese.

- .github/workflows/deploy.yml
- Dockerfile
This uses the github container registry for publishing the image fly pulls. This should have the same result as doing what we are doing now, but with better cache and the ability to pull the images down locally to test.
> chore: use ghcr for docker image building and publishing
