elixirschool/school_house

config/config.exs
config/test.exs
lib/school_house/lessons.ex
lib/school_house/posts.ex
test/school_house/lessons_test.exs
test/school_house/posts_test.exs
test/support/content/lessons/en/basics/basics.md
test/support/content/lessons/es/basics/basics.md
test/support/content/posts/test_blog_post.md

The goal of this PR is multifaceted: 
1. Make testing easier by shifting the dependency on content to a smaller, faster to compile, and known set of content. This collection can grow to enable better testing but can remain much smaller in size than the total collection.
2. Add test coverage for the modules implementing NimblePublisher and handling our content.

Testing enhancements

---

.github/CODEOWNERS

We can later update this to the developers group but to reduce the noise
for everyone else, I've kept this to the small group actively working on
it.

Update CODEOWNERS for initial development group

---

config/lessons.exs
lib/school_house_web/templates/layout/_lesson_menu.html.leex

Small change to reflect what the lesson is actually called in the content repo.

Update Ecto basics config

---

lib/school_house_web/templates/layout/_footer.html.leex
lib/school_house_web/views/html_helpers.ex

Got carried away with fixing the `href` to @doomspork's twitter feed. In addition...
- Mobile first 2 columns, with `xl` breakpoint being 4 columns
- Added social links to Elixir School twitter feed, and github page
- Added some useful links

Update footer to be responsive

---

.github/workflows/ci.yml

Exploring using the erlef action :+1:

Simplify Actions with erlef/setup-beam

---

lib/school_house_web/templates/layout/_footer.html.leex
lib/school_house_web/templates/page/index.html.eex

This one closes #18 
Suggestions for better copy are welcomed.

Add blog cta to bottom of index page

---

lib/school_house_web/templates/layout/_lesson_menu.html.leex
lib/school_house_web/templates/layout/app.html.eex
lib/school_house_web/templates/layout/live.html.leex
lib/school_house_web/templates/layout/root.html.leex

Working through some of the errors and warnings from RocketValidator. This is part of #35

HTML errors

---

lib/school_house/content/lesson.ex
test/school_house/content/lesson_test.exs
test/support/content/lessons/en/basics/enum.md

Cleaned up and simplified the TOC generation which is the cause of many weird UI issue and HTML issues raised by RocketValidator.

Refactor table of contents generation

---

lib/school_house/content/lesson.ex
lib/school_house/lessons.ex
lib/school_house_web/controllers/page_controller.ex
lib/school_house_web/controllers/report_controller.ex
lib/school_house_web/router.ex
lib/school_house_web/templates/layout/_footer.html.leex
lib/school_house_web/templates/report/_coming_soon.html.eex
lib/school_house_web/templates/report/_lesson.html.eex
lib/school_house_web/templates/report/_missing.html.eex
lib/school_house_web/templates/report/_section.html.eex
lib/school_house_web/templates/report/report.html.eex
lib/school_house_web/views/html_helpers.ex
lib/school_house_web/views/report_view.ex
priv/gettext/default.pot
priv/gettext/en/LC_MESSAGES/default.po
test/school_house/lessons_test.exs

@gemantzu I know you've been busy so I got started on this. Let me know what you think. You can take over the branch if you want or I can implement the feedback.

Translation report

---

lib/school_house/lessons.ex
lib/school_house_web/controllers/lesson_controller.ex
lib/school_house_web/controllers/page_controller.ex
lib/school_house_web/router.ex
lib/school_house_web/templates/layout/_footer.html.leex
lib/school_house_web/templates/lesson/_advanced.html.eex
lib/school_house_web/templates/lesson/_basics.html.eex
lib/school_house_web/templates/lesson/_data_processing.html.eex
lib/school_house_web/templates/lesson/_ecto.html.eex
lib/school_house_web/templates/lesson/_intermediate.html.eex
lib/school_house_web/templates/lesson/_misc.html.eex
lib/school_house_web/templates/lesson/_storage.html.eex
lib/school_house_web/templates/lesson/_testing.html.eex
lib/school_house_web/templates/lesson/index.html.eex
lib/school_house_web/templates/page/index.html.eex

This should improve our SEO a bit too :tada:

Add new page for listing lessons per section

---

.github/workflows/deploy.yml

See: https://github.community/t/triggering-by-other-repository/16163

Trigger deploys on repository_dispatch

---

lib/school_house_web/templates/layout/_footer.html.leex
lib/school_house_web/templates/layout/_header.html.leex

Delete the contributors link in the footer element for the time being.
Related to https://github.com/elixirschool/school_house/issues/73#issuecomment-879523642

Remove Contributors Link in Footer

---

.github/CODEOWNERS

I'll be happy to come back to the team as I have more availability now )

Add Jaime to CODEOWNERS

---

ROCKET-VALIDATOR.md

I wrote a quick guide to help on the setup of Rocket Validator for new users.

adds Rocket Validator guide

---

lib/school_house_web/controllers/page_controller.ex
lib/school_house_web/router.ex
lib/school_house_web/templates/error/error.html.eex
lib/school_house_web/templates/error/translation_missing.html.eex
lib/school_house_web/templates/layout/_footer.html.leex
lib/school_house_web/templates/layout/_header.html.leex
lib/school_house_web/templates/page/get_involved.html.eex
lib/school_house_web/templates/page/index.html.eex
test/school_house_web/controllers/page_controller_test.exs

Closes #74 .
Adds a page to help potential new contributors get involved with Elixir School!

Add "Get Involved" Page

---

lib/mix/tasks/school_house.gen.sitemap.ex

adds new get_involved page to sitemap.xml

---

ROCKET-VALIDATOR.md

Updates documentation of muting rules used in rocket validator

update muting rules used in rocket validator

---

assets/css/app.css
assets/tailwind.config.js
lib/school_house_web/templates/layout/_footer.html.leex
lib/school_house_web/templates/layout/_locale_menu.html.leex
lib/school_house_web/templates/lesson/lesson.html.eex
lib/school_house_web/templates/page/index.html.eex
lib/school_house_web/templates/post/_post_preview.html.eex

Related to #109.
Updated the syntax highlighting and other text to fix accessibility issues related to low contrast text colors.

Better Text Contrast

---

app.json

Added an `app.json` file with `stack: container` in attempt to get review apps working.

Add App.Json File for Heroku Deploys

---

assets/css/app.css
assets/tailwind.config.js

duplicate of #116
Improvements to color contrast.

Update Colors to Improve Contrast

---

lib/school_house_web/templates/page/index.html.eex

This PR resolves #138 
Considering that this is temporary, I kept the template.

Remove newsletter signup

---

ROCKET-VALIDATOR.md

With link to the latest stats, reports and muting rules

update ROCKET-VALIDATOR.md 

---

assets/tailwind.config.js
lib/school_house_web/templates/page/index.html.heex

fixes #177 
This PR is to add links inside the local section of the intro page.

Add local links in the intro page

---

lib/school_house_web/live/conferences_live.html.heex
lib/school_house_web/templates/lesson/_advanced.html.heex
lib/school_house_web/templates/lesson/_basics.html.heex
lib/school_house_web/templates/lesson/_data_processing.html.heex
lib/school_house_web/templates/lesson/_ecto.html.heex
lib/school_house_web/templates/lesson/_intermediate.html.heex
lib/school_house_web/templates/lesson/_misc.html.heex
lib/school_house_web/templates/lesson/_pagination.html.heex
lib/school_house_web/templates/lesson/_storage.html.heex
lib/school_house_web/templates/lesson/_testing.html.heex
lib/school_house_web/templates/page/podcasts.html.heex
lib/school_house_web/templates/post/index.html.heex

Fix some sections lack heading

---

assets/tailwind.config.js
lib/school_house/content/post.ex
lib/school_house_web/templates/post/_post_preview.html.heex
lib/school_house_web/templates/post/post.html.heex
test/school_house/posts_test.exs

Fixes https://github.com/elixirschool/school_house/issues/187
Before
After
Before
After

Render markdown code blocks

---

assets/css/app.css
config/config.exs
lib/school_house_web/templates/layout/app.html.heex
lib/school_house_web/templates/layout/root.html.heex
lib/school_house_web/views/html_helpers.ex
lib/school_house_web/views/lesson_view.ex
priv/gettext/fa/LC_MESSAGES/default.po

Added support for Persian language. Other right to left languages should also look better now.
**Before Modifications:**
**After Modifications:**

Better support for Persian and other right to left languages

---

assets/tailwind.config.js

Fixes https://github.com/elixirschool/school_house/issues/217
Before
Now

Fix code colors in darkmode

---

assets/css/app.css
assets/js/app.js
assets/js/pickup.js
lib/school_house_web/templates/layout/root.html.heex

#221 had some problem with phone's navbar being pushed down and empty space showing up, so i created a different ui for phones

New UI for phone for "Pick up from where you left of" feature

---

lib/mix/tasks/school_house.gen.rss.ex
lib/school_house/content/post.ex
lib/school_house_web/controllers/post_controller.ex

Fixes https://github.com/elixirschool/school_house/issues/223

Avoid showing HTML tag in page title

---

assets/css/app.css
assets/package-lock.json
assets/package.json
assets/postcss.config.js
config/config.exs
config/test.exs
lib/mix/tasks/school_house.gen.sitemap.ex
lib/school_house/lessons.ex
lib/school_house/locale_info.ex
lib/school_house_web/plugs/set_locale_plug.ex
lib/school_house_web/templates/layout/_locale_menu.html.heex
lib/school_house_web/views/html_helpers.ex
test/school_house/locales_test.exs
test/school_house_web/views/html_helpers_test.exs

Add flag icons and better locale support
